server:
  port: 8080
  servlet:
    application-display-name: SpringBootFakeApi

spring:
  main:
    banner-mode: off


logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html